Timer
lastZu/TSM pull request #16
Opened 2024-04-21 19:09 UTC by lastZu

2024-04-22 08:35 UTC, php5art requested changes

2024-04-22 08:35 UTC, php5art commented on src/TSM.Task.Api/appsettings.Development.json
Нужно добавить этот файл в .gitignore и удалить из репозитория

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Api/Startup.cs
> +            "Host=db;Port=5432;Database=WorkLogDB;Username=tasker;Password=pass"
Вынеси плиз коннекшен стринг в appsettings

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Api/Properties/launchSettings.json
> +}
```suggestion
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "TSM.WorkLogs.Api": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "http://localhost:5253",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
```

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Application/Services/WorkLogs/CreateWorkLogRequest.cs
> +    public Guid? TaskId { get; set; }
Для чего он nullable? Тот же вопрос про Time и Date

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Application/Services/WorkLogs/CreateWorkLogRequest.cs
> +public class CreateWorkLogRequest
делай плиз все классы sealed, если от них не требуется наследовать

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Application/Services/WorkLogs/CreateWorkLogRequest.cs
> +public class CreateWorkLogRequest
Еслине лень, давай все дто(по крайней мере реквесты) переделаем на record вместо class
Можно будет все поля в них сделать так "public string Comment { get; init; }"

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Application/TSM.WorkLogs.Application.csproj
> +  <PropertyGroup>
Вот это перемести плиз наверх

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Domain/Entities/WorkLog.cs
> +    public Guid? TaskId { get; set; }
Зачем это nullable? Могут быть логи не прилинкованные к задачам?

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Domain/Entities/WorkLog.cs
> +    public int? Time { get; set; }
зачем nullable?

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Domain/Entities/WorkLog.cs
> +    public DateTime? Date { get; set; }
зачем nullable?

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Api/appsettings.Development.json
Удали из репозитория и добавь в .gitignore плиз

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Api/Controllers/WorkLogController.cs
> +        return await _workLogService.GetById(request, cancellationToken);
такие штуки можно делать без async/await. Лишние накладные расходы на стейт машину

2024-04-22 08:35 UTC, php5art commented on src/TSM.WorkLogs.Api/Controllers/WorkLogController.cs
> +        return await _workLogService.GetById(request, cancellationToken);
https://medium.com/@deep_blue_day/long-story-short-async-await-best-practices-in-net-1f39d7d84050

2024-04-23 08:45 UTC, lastZu commented on src/TSM.Task.Api/appsettings.Development.json
Сделано

2024-04-23 08:45 UTC, lastZu commented on src/TSM.WorkLogs.Api/Startup.cs
> +            "Host=db;Port=5432;Database=WorkLogDB;Username=tasker;Password=pass"
Сделано

2024-04-23 08:45 UTC, lastZu commented on src/TSM.WorkLogs.Application/Services/WorkLogs/CreateWorkLogRequest.cs
> +    public Guid? TaskId { get; set; }
Сделано

2024-04-23 08:45 UTC, lastZu commented on src/TSM.WorkLogs.Application/Services/WorkLogs/CreateWorkLogRequest.cs
> +public class CreateWorkLogRequest
Сделано

2024-04-23 08:45 UTC, lastZu commented on src/TSM.WorkLogs.Domain/Entities/WorkLog.cs
> +    public Guid? TaskId { get; set; }
Сделано

2024-04-23 08:45 UTC, lastZu commented on src/TSM.WorkLogs.Domain/Entities/WorkLog.cs
> +    public int? Time { get; set; }
Сделано

2024-04-23 08:45 UTC, lastZu commented on src/TSM.WorkLogs.Domain/Entities/WorkLog.cs
> +    public DateTime? Date { get; set; }
Сделано

2024-04-23 08:46 UTC, lastZu commented on src/TSM.WorkLogs.Api/appsettings.Development.json
Сделано

2024-04-23 08:46 UTC, lastZu commented on src/TSM.WorkLogs.Api/Controllers/WorkLogController.cs
> +        return await _workLogService.GetById(request, cancellationToken);
Сделано

2024-04-23 08:49 UTC, merged